import { Item, Store, StoreInventoryItem, Transaction, Department, Program, ProgramIssue } from './types';

export const DEPARTMENTS: Department[] = [
  { id: 'd1', name: 'IYCPM', head: 'Swami Anand' },
  { id: 'd2', name: 'Ashram Program Dept', head: 'Ma Yoga' },
  { id: 'd3', name: 'Hatha Yoga School', head: 'Swami Prem' },
  { id: 'd4', name: 'Puja & Rituals', head: 'Ma Shakti' },
  { id: 'd5', name: 'Ashram Maintenance', head: 'Swami Dhanya' },
  { id: 'd6', name: 'Guest Services', head: 'Ma Prem' },
  { id: 'd7', name: 'Bhiksha Hall (Kitchen)', head: 'Swami Bhojan' },
  { id: 'd8', name: 'IT & Digital', head: 'Ma Tech' },
  { id: 'd9', name: 'Transport & Logistics', head: 'Swami Vahan' },
];

export const PROGRAMS: Program[] = [
  // February 2026
  { id: 'p_feb_1', name: 'Vijji Maa Aradhana', departmentId: 'd2', startDate: '2026-02-01', endDate: '2026-02-01' },
  { id: 'p_feb_2', name: 'Thaipusam', departmentId: 'd4', startDate: '2026-02-01', endDate: '2026-02-01' },
  { id: 'p_feb_3', name: "Ishanga's Guided Silence", departmentId: 'd2', startDate: '2026-02-20', endDate: '2026-02-26' },
  { id: 'p_feb_4', name: 'HYS Silence Upgrade', departmentId: 'd3', startDate: '2026-02-21', endDate: '2026-02-26' },
  { id: 'p_feb_5', name: 'Shoonya Intensive (English) - European Team', departmentId: 'd2', startDate: '2026-02-21', endDate: '2026-02-24' },
  { id: 'p_feb_6', name: 'French Team Visit', departmentId: 'd6', startDate: '2026-02-24', endDate: '2026-02-27' },
  { id: 'p_feb_7', name: 'Brand INSIGHT', departmentId: 'd1', startDate: '2026-02-27', endDate: '2026-03-01' },
  { id: 'p_feb_8', name: 'Bhava Spandana Ladies (English) - European Team', departmentId: 'd2', startDate: '2026-02-27', endDate: '2026-03-02' },
  
  // March 2026
  { id: 'p_mar_1', name: 'Shoonya Intensive (English)', departmentId: 'd2', startDate: '2026-03-04', endDate: '2026-03-07' },
  { id: 'p_mar_2', name: 'Sannidhi Ishanga Upgrade', departmentId: 'd4', startDate: '2026-03-04', endDate: '2026-03-08' },
  { id: 'p_mar_3', name: 'IE Retreat (English)', departmentId: 'd2', startDate: '2026-03-05', endDate: '2026-03-08' },
  { id: 'p_mar_4', name: 'Bhava Spandana Ladies (English)', departmentId: 'd2', startDate: '2026-03-05', endDate: '2026-03-08' },
  { id: 'p_mar_5', name: 'Content Creators Retreat', departmentId: 'd1', startDate: '2026-03-08', endDate: '2026-03-10' },
  { id: 'p_mar_6', name: 'IE Retreat (English)', departmentId: 'd2', startDate: '2026-03-12', endDate: '2026-03-15' },
  { id: 'p_mar_7', name: 'Shoonya Intensive (English)', departmentId: 'd2', startDate: '2026-03-12', endDate: '2026-03-15' },
  { id: 'p_mar_8', name: 'Bhava Spandana Gents (Tamil)', departmentId: 'd2', startDate: '2026-03-12', endDate: '2026-03-15' },
  { id: 'p_mar_9', name: 'Bhava Spandana Gents (English)', departmentId: 'd2', startDate: '2026-03-12', endDate: '2026-03-15' },
  { id: 'p_mar_10', name: 'IE Retreat (English)', departmentId: 'd2', startDate: '2026-03-19', endDate: '2026-03-22' },
  { id: 'p_mar_11', name: 'Shoonya Intensive (Tamil)', departmentId: 'd2', startDate: '2026-03-19', endDate: '2026-03-22' },
  { id: 'p_mar_12', name: 'Bhava Spandana Gents (Hindi)', departmentId: 'd2', startDate: '2026-03-19', endDate: '2026-03-22' },
  { id: 'p_mar_13', name: 'Bhava Spandana Ladies (English)', departmentId: 'd2', startDate: '2026-03-23', endDate: '2026-03-26' },
  { id: 'p_mar_14', name: 'Indian Defence Force Training Program', departmentId: 'd3', startDate: '2026-03-23', endDate: '2026-04-06' },
  { id: 'p_mar_15', name: 'Bhava Spandana Gents (English)', departmentId: 'd2', startDate: '2026-03-24', endDate: '2026-03-27' },
  { id: 'p_mar_16', name: 'Shoonya Intensive (English)', departmentId: 'd2', startDate: '2026-03-25', endDate: '2026-03-28' },
  { id: 'p_mar_17', name: 'IE Retreat (English)', departmentId: 'd2', startDate: '2026-03-26', endDate: '2026-03-29' },
  { id: 'p_mar_18', name: 'Shoonya Intensive (English)', departmentId: 'd2', startDate: '2026-03-28', endDate: '2026-03-31' },
  { id: 'p_mar_19', name: 'Bhava Spandana Ladies (English)', departmentId: 'd2', startDate: '2026-03-30', endDate: '2026-04-02' },
];

export const ITEMS: Item[] = [
  { id: 'tape-100m', name: 'Measurement Tape - 100m', category: 'Tools', unit: 'Nos', totalStock: 10, minThreshold: 2, departmentId: 'd5', store: 'Main Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'mattress-roll', name: 'Korapai Rollable Mattress', category: 'Residential', unit: 'Nos', totalStock: 50, minThreshold: 5, departmentId: 'd6', store: 'Guest Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1634712282287-14ed57b9cc89?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'tiffin-5l', name: 'Tiffin Carrier - 5 Layer - SS - 1.5Ft', category: 'Kitchen', unit: 'Nos', totalStock: 20, minThreshold: 2, departmentId: 'd7', store: 'Kitchen Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1584346133934-a3afd2a33c4c?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'torch-recharge', name: 'Torchlight - Rechargeable', category: 'Tools', unit: 'Nos', totalStock: 15, minThreshold: 3, departmentId: 'd5', store: 'Main Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1590564310418-66304f55a2c2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'emergency-light', name: 'Emergency Light', category: 'Tools', unit: 'Nos', totalStock: 10, minThreshold: 2, departmentId: 'd5', store: 'Main Store', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1517055727180-d15d7a9c84c1?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'kettle-500ml', name: 'Kettle - Electric - 500ml', category: 'Kitchen', unit: 'Nos', totalStock: 8, minThreshold: 1, departmentId: 'd7', store: 'Kitchen Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1594824464562-06085556c5c9?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'tea-masala', name: 'Tea Powder - Masala Flavor - Premix', category: 'Food', unit: 'Sachet', totalStock: 500, minThreshold: 50, departmentId: 'd7', store: 'Kitchen Store', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1594631252845-29fc45865157?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'paper-cup-150ml', name: 'Paper Cup - 150ml', category: 'General', unit: 'Nos', totalStock: 2000, minThreshold: 200, departmentId: 'd6', store: 'Guest Store', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1585342670235-24292ba7b0d2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'flood-light', name: 'Flood Light', category: 'Tools', unit: 'Nos', totalStock: 12, minThreshold: 2, departmentId: 'd5', store: 'Main Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1519750783826-e2420f4d687f?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'cushion-white', name: 'Class Cushion Seat - White', category: 'Residential', unit: 'Nos', totalStock: 200, minThreshold: 20, departmentId: 'd6', store: 'Guest Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'kriya-pad', name: 'Kriya Pad', category: 'Yoga', unit: 'Nos', totalStock: 100, minThreshold: 10, departmentId: 'd3', store: 'HYS Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'carpet-orange', name: 'Carpet - Orange', category: 'Residential', unit: 'Nos', totalStock: 40, minThreshold: 5, departmentId: 'd6', store: 'Guest Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1534889156217-d34a09b434e8?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'masking-tape-3', name: 'Masking Tape - 3"', category: 'Stationery', unit: 'Nos', totalStock: 50, minThreshold: 5, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'packing-tape-3', name: 'Packing Tape - Brown - 3"', category: 'Stationery', unit: 'Nos', totalStock: 30, minThreshold: 5, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'marker-cd-black', name: 'Marker - CD Marker - Black', category: 'Stationery', unit: 'Nos', totalStock: 100, minThreshold: 10, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'val-deposit-form', name: 'Valuables Deposit Form', category: 'Stationery', unit: 'Nos', totalStock: 5000, minThreshold: 500, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1586281380349-631531a744c2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'chart-paper-cream', name: 'Chart Paper - Cream', category: 'Stationery', unit: 'Nos', totalStock: 200, minThreshold: 20, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'box-tray-wooden', name: 'Box Tray - Wooden - With Handle', category: 'Tools', unit: 'Nos', totalStock: 15, minThreshold: 2, departmentId: 'd5', store: 'Main Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1591261730799-ee4e6c2d16d7?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'guru-pooja-set', name: 'Guru Pooja set', category: 'Puja', unit: 'Set', totalStock: 10, minThreshold: 1, departmentId: 'd4', store: 'Puja Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1561488132-831730cad1d5?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'guru-pooja-offerings', name: 'Guru Pooja Offerings Set', category: 'Puja', unit: 'Set', totalStock: 50, minThreshold: 5, departmentId: 'd4', store: 'Puja Store', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1561488132-831730cad1d5?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'lamp-buddha-4', name: 'Lamp - Buddha Lamp - 4"', category: 'Puja', unit: 'Nos', totalStock: 20, minThreshold: 2, departmentId: 'd4', store: 'Puja Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'chimney-glass', name: 'Chimney Glass - Curved - 5 Dia - Lantern Chimney', category: 'Puja', unit: 'Nos', totalStock: 15, minThreshold: 2, departmentId: 'd4', store: 'Puja Store', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1504194104404-433180773017?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'match-box-small', name: 'Match Box - Small', category: 'Puja', unit: 'Nos', totalStock: 100, minThreshold: 10, departmentId: 'd4', store: 'Puja Store', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1595461135849-bf08893fdc2c?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'eraser', name: 'Eraser', category: 'Stationery', unit: 'Nos', totalStock: 150, minThreshold: 20, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'pencil', name: 'Pencil', category: 'Stationery', unit: 'Nos', totalStock: 300, minThreshold: 40, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1512036630240-199126773e73?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'ie-reg', name: 'Inner Engineering - Registration Form (English)', category: 'Stationery', unit: 'Nos', totalStock: 700, minThreshold: 100, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1586281380349-631531a744c2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'ie-comp', name: 'Inner Engineering - Completion Form (English)', category: 'Stationery', unit: 'Nos', totalStock: 700, minThreshold: 100, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1586281380349-631531a744c2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'ier-a5', name: 'IER A5 Paper Sheets - Off White', category: 'Stationery', unit: 'Nos', totalStock: 2000, minThreshold: 200, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'prog-vol', name: 'Program Volunteering Experience Form (English)', category: 'Stationery', unit: 'Nos', totalStock: 250, minThreshold: 50, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1586281380349-631531a744c2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'yoga-mat-premium', name: 'Yoga Mat - Premium - Black', category: 'Yoga', unit: 'Nos', totalStock: 150, minThreshold: 15, departmentId: 'd3', store: 'HYS Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1592432676556-2693b12946f8?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'copper-bottle-1l', name: 'Copper Bottle - 1 Liter', category: 'General', unit: 'Nos', totalStock: 60, minThreshold: 10, departmentId: 'd6', store: 'Guest Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'incense-sandal', name: 'Incense Sticks - Sandalwood', category: 'Puja', unit: 'Box', totalStock: 200, minThreshold: 30, departmentId: 'd4', store: 'Puja Store', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1602847213180-50e43a80eeef?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'white-dhoti', name: 'White Dhoti - Cotton', category: 'Residential', unit: 'Nos', totalStock: 100, minThreshold: 20, departmentId: 'd6', store: 'Guest Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'meditation-shawl', name: 'Meditation Shawl - Woolen', category: 'Residential', unit: 'Nos', totalStock: 80, minThreshold: 15, departmentId: 'd6', store: 'Guest Store', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'stapler', name: 'Stapler - Heavy Duty', category: 'Stationery', unit: 'Nos', totalStock: 20, minThreshold: 2, departmentId: 'd2', store: 'Nalanda', isConsumable: false, imageUrl: 'https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'stapler-pins', name: 'Stapler Pins - 24/6', category: 'Stationery', unit: 'Box', totalStock: 100, minThreshold: 10, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'id-card-holders', name: 'ID Card Holders - Transparent', category: 'Stationery', unit: 'Nos', totalStock: 500, minThreshold: 50, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'lanyard-isha', name: 'Lanyard - Isha Branded', category: 'Stationery', unit: 'Nos', totalStock: 500, minThreshold: 50, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'whiteboard-marker', name: 'Whiteboard Marker - Set of 4', category: 'Stationery', unit: 'Set', totalStock: 40, minThreshold: 5, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=400&h=400' },
  { id: 'a4-paper-ream', name: 'A4 Paper Ream - 75 GSM', category: 'Stationery', unit: 'Ream', totalStock: 100, minThreshold: 10, departmentId: 'd2', store: 'Nalanda', isConsumable: true, imageUrl: 'https://images.unsplash.com/photo-1586075010633-2442dc3d6307?auto=format&fit=crop&q=80&w=400&h=400' },
];

export const STORES: Store[] = [
  { id: 'nalanda', name: 'Nalanda', type: 'office', itemCount: 17, status: 'healthy' },
  { id: 'main-store', name: 'Main Store', type: 'storage', itemCount: 5, status: 'healthy' },
  { id: 'guest-store', name: 'Guest Store', type: 'residential', itemCount: 7, status: 'healthy' },
  { id: 'kitchen-store', name: 'Kitchen Store', type: 'kitchen', itemCount: 4, status: 'healthy' },
  { id: 'hys-store', name: 'HYS Store', type: 'storage', itemCount: 3, status: 'healthy' },
  { id: 'puja-store', name: 'Puja Store', type: 'storage', itemCount: 6, status: 'healthy' },
  { id: 'store2', name: 'Store 2', type: 'storage', itemCount: 3, status: 'healthy' },
];

export const STORE_INVENTORY: StoreInventoryItem[] = [
  { itemId: 'ie-reg', storeId: 'nalanda', quantity: 700, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'ie-comp', storeId: 'nalanda', quantity: 700, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'ier-a5', storeId: 'nalanda', quantity: 2000, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'prog-vol', storeId: 'nalanda', quantity: 250, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'marker-cd-black', storeId: 'nalanda', quantity: 100, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'stapler', storeId: 'nalanda', quantity: 20, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'stapler-pins', storeId: 'nalanda', quantity: 100, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'id-card-holders', storeId: 'nalanda', quantity: 500, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'lanyard-isha', storeId: 'nalanda', quantity: 500, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'whiteboard-marker', storeId: 'nalanda', quantity: 40, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'a4-paper-ream', storeId: 'nalanda', quantity: 100, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'masking-tape-3', storeId: 'nalanda', quantity: 50, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'packing-tape-3', storeId: 'nalanda', quantity: 30, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'val-deposit-form', storeId: 'nalanda', quantity: 5000, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'chart-paper-cream', storeId: 'nalanda', quantity: 200, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'eraser', storeId: 'nalanda', quantity: 150, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'pencil', storeId: 'nalanda', quantity: 300, lastUpdated: '2026-03-01T10:00:00Z' },
  { itemId: 'tape-100m', storeId: 'main-store', quantity: 10, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'torch-recharge', storeId: 'main-store', quantity: 15, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'emergency-light', storeId: 'main-store', quantity: 10, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'flood-light', storeId: 'main-store', quantity: 8, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'box-tray-wooden', storeId: 'main-store', quantity: 5, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'mattress-roll', storeId: 'guest-store', quantity: 50, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'paper-cup-150ml', storeId: 'guest-store', quantity: 2000, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'cushion-white', storeId: 'guest-store', quantity: 200, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'carpet-orange', storeId: 'guest-store', quantity: 40, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'copper-bottle-1l', storeId: 'guest-store', quantity: 60, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'white-dhoti', storeId: 'guest-store', quantity: 100, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'meditation-shawl', storeId: 'guest-store', quantity: 80, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'tiffin-5l', storeId: 'kitchen-store', quantity: 20, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'kettle-500ml', storeId: 'kitchen-store', quantity: 8, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'tea-masala', storeId: 'kitchen-store', quantity: 500, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'paper-cup-150ml', storeId: 'kitchen-store', quantity: 1000, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'kriya-pad', storeId: 'hys-store', quantity: 100, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'yoga-mat-premium', storeId: 'hys-store', quantity: 150, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'cushion-white', storeId: 'hys-store', quantity: 50, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'guru-pooja-set', storeId: 'puja-store', quantity: 10, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'incense-sandal', storeId: 'puja-store', quantity: 200, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'lamp-buddha-4', storeId: 'puja-store', quantity: 20, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'guru-pooja-offerings', storeId: 'puja-store', quantity: 50, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'chimney-glass', storeId: 'puja-store', quantity: 15, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'match-box-small', storeId: 'puja-store', quantity: 100, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'flood-light', storeId: 'store2', quantity: 12, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'box-tray-wooden', storeId: 'store2', quantity: 15, lastUpdated: '2026-02-21T10:00:00Z' },
  { itemId: 'tape-100m', storeId: 'store2', quantity: 2, lastUpdated: '2026-02-21T10:00:00Z' },
];

export const TRANSACTIONS: Transaction[] = [
  { id: 't1', type: 'restock', itemId: 'eraser', itemName: 'Eraser', quantity: 100, toStoreId: 'nalanda', timestamp: '2026-02-23T09:00:00Z', user: 'Admin', note: 'Monthly restock', purchaseCode: '40144269' },
  { id: 't2', type: 'restock', itemId: 'pencil', itemName: 'Pencil', quantity: 200, toStoreId: 'nalanda', timestamp: '2026-02-23T09:15:00Z', user: 'Admin', note: 'Monthly restock', purchaseCode: '40138495' },
  { id: 't3', type: 'restock', itemId: 'chart-paper-cream', itemName: 'Chart Paper - Cream', quantity: 16, toStoreId: 'nalanda', timestamp: '2026-02-23T10:00:00Z', user: 'Admin', note: 'Special request', purchaseCode: '40155629' },
  { id: 't4', type: 'checkout', itemId: 'ie-reg', itemName: 'Inner Engineering - Registration Form (English)', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_1', timestamp: '2026-03-04T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't5', type: 'checkout', itemId: 'id-card-holders', itemName: 'ID Card Holders - Transparent', quantity: 110, fromStoreId: 'nalanda', toStoreId: 'p_mar_3', timestamp: '2026-03-05T08:30:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't6', type: 'checkout', itemId: 'lanyard-isha', itemName: 'Lanyard - Isha Branded', quantity: 110, fromStoreId: 'nalanda', toStoreId: 'p_mar_3', timestamp: '2026-03-05T08:30:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't7', type: 'checkout', itemId: 'a4-paper-ream', itemName: 'A4 Paper Ream - 75 GSM', quantity: 2, fromStoreId: 'nalanda', toStoreId: 'p_mar_1', timestamp: '2026-03-04T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't8', type: 'checkout', itemId: 'whiteboard-marker', itemName: 'Whiteboard Marker - Set of 4', quantity: 5, fromStoreId: 'nalanda', toStoreId: 'p_mar_1', timestamp: '2026-03-04T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't9', type: 'checkout', itemId: 'stapler', itemName: 'Stapler - Heavy Duty', quantity: 2, fromStoreId: 'nalanda', toStoreId: 'p_mar_10', timestamp: '2026-03-19T08:00:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't10', type: 'checkout', itemId: 'marker-cd-black', itemName: 'Marker - CD Marker - Black', quantity: 20, fromStoreId: 'nalanda', toStoreId: 'p_mar_5', timestamp: '2026-03-08T09:00:00Z', user: 'Admin', note: 'Issued for Content Creators Retreat' },
  { id: 't11', type: 'transfer', itemId: 'a4-paper-ream', itemName: 'A4 Paper Ream - 75 GSM', quantity: 50, fromStoreId: 'main-store', toStoreId: 'nalanda', timestamp: '2026-03-01T09:00:00Z', user: 'Admin', note: 'Bulk stock replenishment' },
  { id: 't12', type: 'transfer', itemId: 'emergency-light', itemName: 'Emergency Light', quantity: 10, fromStoreId: 'main-store', toStoreId: 'guest-store', timestamp: '2026-03-01T10:30:00Z', user: 'Admin', note: 'Safety equipment distribution' },
  { id: 't13', type: 'transfer', itemId: 'cushion-white', itemName: 'Class Cushion Seat - White', quantity: 100, fromStoreId: 'guest-store', toStoreId: 'hys-store', timestamp: '2026-03-02T14:00:00Z', user: 'Admin', note: 'Moving stock for upcoming programs' },
  { id: 't14', type: 'transfer', itemId: 'match-box-small', itemName: 'Match Box - Small', quantity: 50, fromStoreId: 'main-store', toStoreId: 'puja-store', timestamp: '2026-03-02T15:00:00Z', user: 'Admin', note: 'Puja store replenishment' },
  { id: 't15', type: 'transfer', itemId: 'incense-sandal', itemName: 'Incense Sticks - Sandalwood', quantity: 50, fromStoreId: 'main-store', toStoreId: 'puja-store', timestamp: '2026-03-02T15:15:00Z', user: 'Admin', note: 'Puja store replenishment' },
  { id: 't16', type: 'checkout', itemId: 'pencil', itemName: 'Pencil', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_1', timestamp: '2026-03-04T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't17', type: 'checkout', itemId: 'eraser', itemName: 'Eraser', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_1', timestamp: '2026-03-04T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't18', type: 'checkout', itemId: 'ie-reg', itemName: 'Inner Engineering - Registration Form (English)', quantity: 110, fromStoreId: 'nalanda', toStoreId: 'p_mar_3', timestamp: '2026-03-05T08:30:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't19', type: 'checkout', itemId: 'ie-comp', itemName: 'Inner Engineering - Completion Form (English)', quantity: 110, fromStoreId: 'nalanda', toStoreId: 'p_mar_3', timestamp: '2026-03-05T08:30:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't20', type: 'checkout', itemId: 'cushion-white', itemName: 'Class Cushion Seat - White', quantity: 125, fromStoreId: 'guest-store', toStoreId: 'p_mar_4', timestamp: '2026-03-05T10:00:00Z', user: 'Admin', note: 'Issued for Bhava Spandana' },
  { id: 't21', type: 'checkout', itemId: 'carpet-orange', itemName: 'Carpet - Orange', quantity: 20, fromStoreId: 'guest-store', toStoreId: 'p_mar_4', timestamp: '2026-03-05T10:00:00Z', user: 'Admin', note: 'Issued for Bhava Spandana' },
  { id: 't22', type: 'checkout', itemId: 'guru-pooja-offerings', itemName: 'Guru Pooja Offerings Set', quantity: 5, fromStoreId: 'puja-store', toStoreId: 'p_mar_2', timestamp: '2026-03-04T11:00:00Z', user: 'Admin', note: 'Issued for Sannidhi Ishanga' },
  { id: 't23', type: 'checkout', itemId: 'match-box-small', itemName: 'Match Box - Small', quantity: 10, fromStoreId: 'puja-store', toStoreId: 'p_mar_2', timestamp: '2026-03-04T11:05:00Z', user: 'Admin', note: 'Issued for Sannidhi Ishanga' },
  { id: 't24', type: 'checkout', itemId: 'ie-reg', itemName: 'Inner Engineering - Registration Form (English)', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_16', timestamp: '2026-03-25T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't25', type: 'checkout', itemId: 'pencil', itemName: 'Pencil', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_16', timestamp: '2026-03-25T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't26', type: 'checkout', itemId: 'mattress-roll', itemName: 'Korapai Rollable Mattress', quantity: 150, fromStoreId: 'guest-store', toStoreId: 'p_mar_16', timestamp: '2026-03-25T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't27', type: 'checkout', itemId: 'eraser', itemName: 'Eraser', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_16', timestamp: '2026-03-25T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't28', type: 'checkout', itemId: 'id-card-holders', itemName: 'ID Card Holders - Transparent', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_16', timestamp: '2026-03-25T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't29', type: 'checkout', itemId: 'lanyard-isha', itemName: 'Lanyard - Isha Branded', quantity: 150, fromStoreId: 'nalanda', toStoreId: 'p_mar_16', timestamp: '2026-03-25T08:00:00Z', user: 'Admin', note: 'Issued for Shoonya Intensive' },
  { id: 't30', type: 'checkout', itemId: 'ie-reg', itemName: 'Inner Engineering - Registration Form (English)', quantity: 100, fromStoreId: 'nalanda', toStoreId: 'p_mar_10', timestamp: '2026-03-19T08:00:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't31', type: 'checkout', itemId: 'pencil', itemName: 'Pencil', quantity: 100, fromStoreId: 'nalanda', toStoreId: 'p_mar_10', timestamp: '2026-03-19T08:00:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't32', type: 'checkout', itemId: 'eraser', itemName: 'Eraser', quantity: 100, fromStoreId: 'nalanda', toStoreId: 'p_mar_10', timestamp: '2026-03-19T08:00:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't33', type: 'checkout', itemId: 'a4-paper-ream', itemName: 'A4 Paper Ream - 75 GSM', quantity: 5, fromStoreId: 'nalanda', toStoreId: 'p_mar_5', timestamp: '2026-03-08T09:00:00Z', user: 'Admin', note: 'Issued for Content Creators Retreat' },
  { id: 't34', type: 'checkout', itemId: 'pencil', itemName: 'Pencil', quantity: 20, fromStoreId: 'nalanda', toStoreId: 'p_mar_5', timestamp: '2026-03-08T09:00:00Z', user: 'Admin', note: 'Issued for Content Creators Retreat' },
  { id: 't35', type: 'checkout', itemId: 'eraser', itemName: 'Eraser', quantity: 20, fromStoreId: 'nalanda', toStoreId: 'p_mar_5', timestamp: '2026-03-08T09:00:00Z', user: 'Admin', note: 'Issued for Content Creators Retreat' },
  { id: 't36', type: 'checkout', itemId: 'pencil', itemName: 'Pencil', quantity: 110, fromStoreId: 'nalanda', toStoreId: 'p_mar_3', timestamp: '2026-03-05T08:30:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't37', type: 'checkout', itemId: 'eraser', itemName: 'Eraser', quantity: 110, fromStoreId: 'nalanda', toStoreId: 'p_mar_3', timestamp: '2026-03-05T08:30:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't38', type: 'checkout', itemId: 'stapler-pins', itemName: 'Stapler Pins - 24/6', quantity: 10, fromStoreId: 'nalanda', toStoreId: 'p_mar_3', timestamp: '2026-03-05T08:30:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't39', type: 'checkout', itemId: 'id-card-holders', itemName: 'ID Card Holders - Transparent', quantity: 100, fromStoreId: 'nalanda', toStoreId: 'p_mar_10', timestamp: '2026-03-19T08:00:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't40', type: 'checkout', itemId: 'lanyard-isha', itemName: 'Lanyard - Isha Branded', quantity: 100, fromStoreId: 'nalanda', toStoreId: 'p_mar_10', timestamp: '2026-03-19T08:00:00Z', user: 'Admin', note: 'Issued for IE Retreat' },
  { id: 't41', type: 'checkout', itemId: 'whiteboard-marker', itemName: 'Whiteboard Marker - Set of 4', quantity: 2, fromStoreId: 'nalanda', toStoreId: 'p_mar_5', timestamp: '2026-03-08T09:00:00Z', user: 'Admin', note: 'Issued for Content Creators Retreat' },
  { id: 't42', type: 'checkout', itemId: 'stapler', itemName: 'Stapler - Heavy Duty', quantity: 1, fromStoreId: 'nalanda', toStoreId: 'p_mar_5', timestamp: '2026-03-08T09:00:00Z', user: 'Admin', note: 'Issued for Content Creators Retreat' },
  { id: 't43', type: 'adjustment', itemId: 'pencil', itemName: 'Pencil', quantity: -5, fromStoreId: 'nalanda', timestamp: '2026-03-06T14:00:00Z', user: 'Admin', note: 'Damaged stock found during weekly check' },
  { id: 't44', type: 'adjustment', itemId: 'eraser', itemName: 'Eraser', quantity: 2, fromStoreId: 'nalanda', timestamp: '2026-03-06T14:10:00Z', user: 'Admin', note: 'Found extra items during physical count' },
  { id: 't45', type: 'restock', itemId: 'a4-paper-ream', itemName: 'A4 Paper Ream - 75 GSM', quantity: 100, toStoreId: 'main-store', timestamp: '2026-03-07T10:00:00Z', user: 'Admin', note: 'Quarterly bulk purchase', purchaseCode: '40166782' },
  { id: 't46', type: 'transfer', itemId: 'id-card-holders', itemName: 'ID Card Holders - Transparent', quantity: 500, fromStoreId: 'main-store', toStoreId: 'nalanda', timestamp: '2026-03-07T11:30:00Z', user: 'Admin', note: 'Replenishing Nalanda stock' },
  { id: 't47', type: 'transfer', itemId: 'lanyard-isha', itemName: 'Lanyard - Isha Branded', quantity: 500, fromStoreId: 'main-store', toStoreId: 'nalanda', timestamp: '2026-03-07T11:45:00Z', user: 'Admin', note: 'Replenishing Nalanda stock' },
  { id: 't48', type: 'checkout', itemId: 'guru-pooja-offerings', itemName: 'Guru Pooja Offerings Set', quantity: 2, fromStoreId: 'puja-store', toStoreId: 'p_mar_12', timestamp: '2026-03-07T08:00:00Z', user: 'Admin', note: 'Issued for Sannidhi Ishanga' },
  { id: 't49', type: 'return', itemId: 'stapler', itemName: 'Stapler - Heavy Duty', quantity: 2, fromStoreId: 'p_mar_1', toStoreId: 'nalanda', timestamp: '2026-03-07T16:00:00Z', user: 'Admin', note: 'Returned after Shoonya Intensive' },
  { id: 't50', type: 'return', itemId: 'whiteboard-marker', itemName: 'Whiteboard Marker - Set of 4', quantity: 3, fromStoreId: 'p_mar_1', toStoreId: 'nalanda', timestamp: '2026-03-07T16:15:00Z', user: 'Admin', note: 'Returned after Shoonya Intensive (2 markers dried up)' },
  { id: 't51', type: 'adjustment', itemId: 'emergency-light', itemName: 'Emergency Light', quantity: -1, fromStoreId: 'guest-store', timestamp: '2026-03-06T15:00:00Z', user: 'Admin', note: 'Broken unit discarded' },
  { id: 't52', type: 'transfer', itemId: 'mattress-roll', itemName: 'Korapai Rollable Mattress', quantity: 50, fromStoreId: 'main-store', toStoreId: 'guest-store', timestamp: '2026-03-05T14:00:00Z', user: 'Admin', note: 'Moving stock for upcoming programs' },
  { id: 't53', type: 'restock', itemId: 'match-box-small', itemName: 'Match Box - Small', quantity: 200, toStoreId: 'main-store', timestamp: '2026-03-04T09:00:00Z', user: 'Admin', note: 'Stock replenishment', purchaseCode: '40177891' },
  { id: 't54', type: 'checkout', itemId: 'incense-sandal', itemName: 'Incense Sticks - Sandalwood', quantity: 10, fromStoreId: 'puja-store', toStoreId: 'p_mar_2', timestamp: '2026-03-04T11:10:00Z', user: 'Admin', note: 'Issued for Sannidhi Ishanga' },
  { id: 't55', type: 'return', itemId: 'cushion-white', itemName: 'Class Cushion Seat - White', quantity: 125, fromStoreId: 'p_mar_4', toStoreId: 'guest-store', timestamp: '2026-03-06T10:00:00Z', user: 'Admin', note: 'Returned after Bhava Spandana' },
  { id: 't56', type: 'return', itemId: 'carpet-orange', itemName: 'Carpet - Orange', quantity: 20, fromStoreId: 'p_mar_4', toStoreId: 'guest-store', timestamp: '2026-03-06T10:15:00Z', user: 'Admin', note: 'Returned after Bhava Spandana' },
  { id: 't57', type: 'transfer', itemId: 'stapler-pins', itemName: 'Stapler Pins - 24/6', quantity: 50, fromStoreId: 'main-store', toStoreId: 'nalanda', timestamp: '2026-03-03T10:00:00Z', user: 'Admin', note: 'Bulk replenishment' },
  { id: 't58', type: 'adjustment', itemId: 'chart-paper-cream', itemName: 'Chart Paper - Cream', quantity: -1, fromStoreId: 'nalanda', timestamp: '2026-03-02T09:30:00Z', user: 'Admin', note: 'Water damage' },
  { id: 't59', type: 'restock', itemId: 'emergency-light', itemName: 'Emergency Light', quantity: 20, toStoreId: 'main-store', timestamp: '2026-02-28T11:00:00Z', user: 'Admin', note: 'New safety equipment batch', purchaseCode: '40188902' },
  { id: 't60', type: 'checkout', itemId: 'ie-reg', itemName: 'Inner Engineering - Registration Form (English)', quantity: 50, fromStoreId: 'nalanda', toStoreId: 'p_mar_1', timestamp: '2026-03-04T08:00:00Z', user: 'Admin', note: 'Additional forms for Shoonya' },
];

export const PROGRAM_ISSUES: ProgramIssue[] = [
  {
    id: 'pi1',
    programId: 'p_mar_1',
    itemId: 'tape-100m',
    itemName: 'Measurement Tape - 100m',
    unit: 'Nos',
    date: '2026-03-04',
    expectedReturnDate: '2026-03-07',
    collectedBy: 'Anandasakthi',
    issuer: 'Self',
    issued: 1,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 1,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Anandasakthi',
    isConsumable: false
  },
  {
    id: 'pi2',
    programId: 'p_mar_2',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-04',
    expectedReturnDate: '2026-03-08',
    collectedBy: 'Yash',
    phone: '8369110104',
    issuer: 'Nikhil',
    issued: 2,
    returned: 2,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '✅ All Returned',
    pocName: 'Yash',
    isConsumable: false
  },
  {
    id: 'pi3',
    programId: 'p_feb_3',
    itemId: 'masking-tape-3',
    itemName: 'Masking Tape - 3"',
    unit: 'Nos',
    date: '2026-02-20',
    collectedBy: 'Ankitha',
    issuer: 'Mano',
    issued: 1,
    returned: 0,
    noReturn: 1,
    exchange: 0,
    consumed: 1,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Ankitha',
    isConsumable: true
  },
  {
    id: 'pi4',
    programId: 'p_feb_4',
    itemId: 'masking-tape-3',
    itemName: 'Masking Tape - 3"',
    unit: 'Nos',
    date: '2026-02-21',
    expectedReturnDate: '2026-02-26',
    collectedBy: 'Narayanan',
    issuer: 'Nikhil',
    issued: 4,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 4,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: true
  },
  {
    id: 'pi5',
    programId: 'p_feb_5',
    itemId: 'torch-recharge',
    itemName: 'Torchlight - Rechargeable',
    unit: 'Nos',
    date: '2026-02-21',
    expectedReturnDate: '2026-02-24',
    collectedBy: 'Suresh',
    issuer: 'Admin',
    issued: 5,
    returned: 2,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 3,
    status: '⚠️ Partially Returned',
    pocName: 'Suresh',
    isConsumable: false
  },
  {
    id: 'pi6',
    programId: 'p_feb_7',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-02-27',
    expectedReturnDate: '2026-03-01',
    collectedBy: 'Meena',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 100,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Meena',
    isConsumable: false
  },
  {
    id: 'pi7',
    programId: 'p_feb_1',
    itemId: 'kettle-500ml',
    itemName: 'Kettle - Electric - 500ml',
    unit: 'Nos',
    date: '2026-02-01',
    expectedReturnDate: '2026-02-01',
    collectedBy: 'Rahul',
    issuer: 'Admin',
    issued: 2,
    returned: 2,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '✅ All Returned',
    pocName: 'Rahul',
    isConsumable: false
  },
  {
    id: 'pi8',
    programId: 'p_feb_2',
    itemId: 'marker-cd-black',
    itemName: 'Marker - CD Marker - Black',
    unit: 'Nos',
    date: '2026-02-01',
    collectedBy: 'Priya',
    issuer: 'Admin',
    issued: 10,
    returned: 0,
    noReturn: 10,
    exchange: 0,
    consumed: 10,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Priya',
    isConsumable: true
  },
  {
    id: 'pi9',
    programId: 'p_mar_14',
    itemId: 'yoga-mat-premium',
    itemName: 'Yoga Mat - Premium - Black',
    unit: 'Nos',
    date: '2026-03-23',
    expectedReturnDate: '2026-04-06',
    collectedBy: 'Swami Dhanya',
    issuer: 'Admin',
    issued: 50,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 50,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Swami Dhanya',
    isConsumable: false
  },
  {
    id: 'pi10',
    programId: 'p_mar_1',
    itemId: 'incense-sandal',
    itemName: 'Incense Sticks - Sandalwood',
    unit: 'Box',
    date: '2026-03-04',
    collectedBy: 'Ma Prem',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 20,
    exchange: 0,
    consumed: 20,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Ma Prem',
    isConsumable: true
  },
  {
    id: 'pi11',
    programId: 'p_mar_1',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-04',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi12',
    programId: 'p_mar_3',
    itemId: 'id-card-holders',
    itemName: 'ID Card Holders - Transparent',
    unit: 'Nos',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi13',
    programId: 'p_mar_3',
    itemId: 'lanyard-isha',
    itemName: 'Lanyard - Isha Branded',
    unit: 'Nos',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi14',
    programId: 'p_mar_4',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-05',
    expectedReturnDate: '2026-03-08',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi15',
    programId: 'p_mar_1',
    itemId: 'a4-paper-ream',
    itemName: 'A4 Paper Ream - 75 GSM',
    unit: 'Ream',
    date: '2026-03-04',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 2,
    returned: 0,
    noReturn: 2,
    exchange: 0,
    consumed: 2,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi16',
    programId: 'p_mar_2',
    itemId: 'guru-pooja-set',
    itemName: 'Guru Pooja set',
    unit: 'Set',
    date: '2026-03-04',
    expectedReturnDate: '2026-03-08',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 1,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 1,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi17',
    programId: 'p_mar_14',
    itemId: 'yoga-mat-premium',
    itemName: 'Yoga Mat - Premium - Black',
    unit: 'Nos',
    date: '2026-03-23',
    expectedReturnDate: '2026-04-06',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 200,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 200,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi18',
    programId: 'p_mar_12',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-19',
    expectedReturnDate: '2026-03-22',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi19',
    programId: 'p_mar_11',
    itemId: 'paper-cup-150ml',
    itemName: 'Paper Cup - 150ml',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 500,
    returned: 0,
    noReturn: 500,
    exchange: 0,
    consumed: 500,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi20',
    programId: 'p_mar_10',
    itemId: 'stapler',
    itemName: 'Stapler - Heavy Duty',
    unit: 'Nos',
    date: '2026-03-19',
    expectedReturnDate: '2026-03-22',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 2,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 2,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi21',
    programId: 'p_mar_5',
    itemId: 'marker-cd-black',
    itemName: 'Marker - CD Marker - Black',
    unit: 'Nos',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 20,
    exchange: 0,
    consumed: 20,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi22',
    programId: 'p_mar_8',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi23',
    programId: 'p_mar_9',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi24',
    programId: 'p_mar_13',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-23',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 125,
    exchange: 0,
    consumed: 125,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi25',
    programId: 'p_mar_6',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-12',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi26',
    programId: 'p_mar_6',
    itemId: 'whiteboard-marker',
    itemName: 'Whiteboard Marker - Set of 4',
    unit: 'Set',
    date: '2026-03-12',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 5,
    exchange: 0,
    consumed: 5,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi27',
    programId: 'p_mar_7',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-12',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi28',
    programId: 'p_mar_7',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi29',
    programId: 'p_mar_8',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi30',
    programId: 'p_mar_8',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi31',
    programId: 'p_mar_11',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 120,
    returned: 0,
    noReturn: 120,
    exchange: 0,
    consumed: 120,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi32',
    programId: 'p_mar_12',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-19',
    expectedReturnDate: '2026-03-22',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 130,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 130,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi33',
    programId: 'p_mar_12',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-19',
    expectedReturnDate: '2026-03-22',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 130,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 130,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi34',
    programId: 'p_mar_15',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-24',
    expectedReturnDate: '2026-03-27',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 140,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 140,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi35',
    programId: 'p_mar_15',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-24',
    expectedReturnDate: '2026-03-27',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 140,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 140,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi36',
    programId: 'p_mar_1',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-04',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi37',
    programId: 'p_mar_1',
    itemId: 'eraser',
    itemName: 'Eraser',
    unit: 'Nos',
    date: '2026-03-04',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi38',
    programId: 'p_mar_3',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi39',
    programId: 'p_mar_3',
    itemId: 'ie-comp',
    itemName: 'Inner Engineering - Completion Form (English)',
    unit: 'Nos',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi40',
    programId: 'p_mar_3',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi41',
    programId: 'p_mar_4',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-05',
    expectedReturnDate: '2026-03-08',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi42',
    programId: 'p_mar_4',
    itemId: 'carpet-orange',
    itemName: 'Carpet - Orange',
    unit: 'Nos',
    date: '2026-03-05',
    expectedReturnDate: '2026-03-08',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 20,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi43',
    programId: 'p_mar_5',
    itemId: 'a4-paper-ream',
    itemName: 'A4 Paper Ream - 75 GSM',
    unit: 'Ream',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 5,
    exchange: 0,
    consumed: 5,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi44',
    programId: 'p_mar_5',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 20,
    exchange: 0,
    consumed: 20,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi45',
    programId: 'p_mar_6',
    itemId: 'id-card-holders',
    itemName: 'ID Card Holders - Transparent',
    unit: 'Nos',
    date: '2026-03-12',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi46',
    programId: 'p_mar_6',
    itemId: 'lanyard-isha',
    itemName: 'Lanyard - Isha Branded',
    unit: 'Nos',
    date: '2026-03-12',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi47',
    programId: 'p_mar_7',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi48',
    programId: 'p_mar_9',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi49',
    programId: 'p_mar_10',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi50',
    programId: 'p_mar_10',
    itemId: 'id-card-holders',
    itemName: 'ID Card Holders - Transparent',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi51',
    programId: 'p_mar_11',
    itemId: 'whiteboard-marker',
    itemName: 'Whiteboard Marker - Set of 4',
    unit: 'Set',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 5,
    exchange: 0,
    consumed: 5,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi52',
    programId: 'p_mar_13',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-23',
    expectedReturnDate: '2026-03-26',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi53',
    programId: 'p_mar_13',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-23',
    expectedReturnDate: '2026-03-26',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi54',
    programId: 'p_mar_14',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-23',
    expectedReturnDate: '2026-04-06',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 200,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 200,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi55',
    programId: 'p_mar_15',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-24',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 140,
    returned: 0,
    noReturn: 140,
    exchange: 0,
    consumed: 140,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi56',
    programId: 'p_mar_2',
    itemId: 'guru-pooja-offerings',
    itemName: 'Guru Pooja Offerings Set',
    unit: 'Set',
    date: '2026-03-04',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 5,
    exchange: 0,
    consumed: 5,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Narayanan',
    isConsumable: true
  },
  {
    id: 'pi57',
    programId: 'p_mar_2',
    itemId: 'match-box-small',
    itemName: 'Match Box - Small',
    unit: 'Nos',
    date: '2026-03-04',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 10,
    returned: 0,
    noReturn: 10,
    exchange: 0,
    consumed: 10,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Narayanan',
    isConsumable: true
  },
  {
    id: 'pi58',
    programId: 'p_mar_4',
    itemId: 'copper-bottle-1l',
    itemName: 'Copper Bottle - 1 Liter',
    unit: 'Nos',
    date: '2026-03-05',
    expectedReturnDate: '2026-03-08',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 5,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi59',
    programId: 'p_mar_5',
    itemId: 'whiteboard-marker',
    itemName: 'Whiteboard Marker - Set of 4',
    unit: 'Set',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 2,
    returned: 0,
    noReturn: 2,
    exchange: 0,
    consumed: 2,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi60',
    programId: 'p_mar_8',
    itemId: 'carpet-orange',
    itemName: 'Carpet - Orange',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 20,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi61',
    programId: 'p_mar_9',
    itemId: 'carpet-orange',
    itemName: 'Carpet - Orange',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 20,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi62',
    programId: 'p_mar_12',
    itemId: 'carpet-orange',
    itemName: 'Carpet - Orange',
    unit: 'Nos',
    date: '2026-03-19',
    expectedReturnDate: '2026-03-22',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 20,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi63',
    programId: 'p_mar_14',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-23',
    expectedReturnDate: '2026-04-06',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 200,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 200,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi64',
    programId: 'p_mar_15',
    itemId: 'carpet-orange',
    itemName: 'Carpet - Orange',
    unit: 'Nos',
    date: '2026-03-24',
    expectedReturnDate: '2026-03-27',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 20,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi65',
    programId: 'p_mar_1',
    itemId: 'stapler',
    itemName: 'Stapler - Heavy Duty',
    unit: 'Nos',
    date: '2026-03-04',
    expectedReturnDate: '2026-03-07',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 2,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 2,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi66',
    programId: 'p_mar_3',
    itemId: 'stapler',
    itemName: 'Stapler - Heavy Duty',
    unit: 'Nos',
    date: '2026-03-05',
    expectedReturnDate: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 2,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 2,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi67',
    programId: 'p_mar_1',
    itemId: 'marker-cd-black',
    itemName: 'Marker - CD Marker - Black',
    unit: 'Nos',
    date: '2026-03-04',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 10,
    returned: 0,
    noReturn: 10,
    exchange: 0,
    consumed: 10,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi68',
    programId: 'p_mar_8',
    itemId: 'torch-recharge',
    itemName: 'Torchlight - Rechargeable',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 5,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi69',
    programId: 'p_mar_9',
    itemId: 'torch-recharge',
    itemName: 'Torchlight - Rechargeable',
    unit: 'Nos',
    date: '2026-03-12',
    expectedReturnDate: '2026-03-15',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 5,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi70',
    programId: 'p_mar_12',
    itemId: 'torch-recharge',
    itemName: 'Torchlight - Rechargeable',
    unit: 'Nos',
    date: '2026-03-19',
    expectedReturnDate: '2026-03-22',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 5,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
  {
    id: 'pi71',
    programId: 'p_mar_14',
    itemId: 'emergency-light',
    itemName: 'Emergency Light',
    unit: 'Nos',
    date: '2026-03-23',
    expectedReturnDate: '2026-04-06',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 10,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 10,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: true
  },
  {
    id: 'pi72',
    programId: 'p_mar_16',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi73',
    programId: 'p_mar_16',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi74',
    programId: 'p_mar_16',
    itemId: 'eraser',
    itemName: 'Eraser',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi75',
    programId: 'p_mar_16',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-25',
    expectedReturnDate: '2026-03-28',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi76',
    programId: 'p_mar_17',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-26',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi77',
    programId: 'p_mar_17',
    itemId: 'id-card-holders',
    itemName: 'ID Card Holders - Transparent',
    unit: 'Nos',
    date: '2026-03-26',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi78',
    programId: 'p_mar_17',
    itemId: 'lanyard-isha',
    itemName: 'Lanyard - Isha Branded',
    unit: 'Nos',
    date: '2026-03-26',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi79',
    programId: 'p_mar_17',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-26',
    expectedReturnDate: '2026-03-29',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 110,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi80',
    programId: 'p_mar_18',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-28',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi81',
    programId: 'p_mar_18',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-28',
    expectedReturnDate: '2026-03-31',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi82',
    programId: 'p_mar_18',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-28',
    expectedReturnDate: '2026-03-31',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 150,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi83',
    programId: 'p_mar_18',
    itemId: 'whiteboard-marker',
    itemName: 'Whiteboard Marker - Set of 4',
    unit: 'Set',
    date: '2026-03-28',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 5,
    exchange: 0,
    consumed: 5,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi84',
    programId: 'p_mar_19',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-30',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 125,
    exchange: 0,
    consumed: 125,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi85',
    programId: 'p_mar_19',
    itemId: 'mattress-roll',
    itemName: 'Korapai Rollable Mattress',
    unit: 'Nos',
    date: '2026-03-30',
    expectedReturnDate: '2026-04-02',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi86',
    programId: 'p_mar_19',
    itemId: 'cushion-white',
    itemName: 'Class Cushion Seat - White',
    unit: 'Nos',
    date: '2026-03-30',
    expectedReturnDate: '2026-04-02',
    collectedBy: 'Narayanan',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 125,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Narayanan',
    isConsumable: false
  },
  {
    id: 'pi87',
    programId: 'p_mar_19',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-30',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 125,
    returned: 0,
    noReturn: 125,
    exchange: 0,
    consumed: 125,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi88',
    programId: 'p_mar_16',
    itemId: 'eraser',
    itemName: 'Eraser',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi89',
    programId: 'p_mar_16',
    itemId: 'id-card-holders',
    itemName: 'ID Card Holders - Transparent',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi90',
    programId: 'p_mar_16',
    itemId: 'lanyard-isha',
    itemName: 'Lanyard - Isha Branded',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi91',
    programId: 'p_mar_10',
    itemId: 'ie-reg',
    itemName: 'Inner Engineering - Registration Form (English)',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi92',
    programId: 'p_mar_10',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi93',
    programId: 'p_mar_10',
    itemId: 'eraser',
    itemName: 'Eraser',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi94',
    programId: 'p_mar_5',
    itemId: 'a4-paper-ream',
    itemName: 'A4 Paper Ream - 75 GSM',
    unit: 'Ream',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 5,
    returned: 0,
    noReturn: 5,
    exchange: 0,
    consumed: 5,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi95',
    programId: 'p_mar_5',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 20,
    exchange: 0,
    consumed: 20,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi96',
    programId: 'p_mar_5',
    itemId: 'eraser',
    itemName: 'Eraser',
    unit: 'Nos',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 20,
    returned: 0,
    noReturn: 20,
    exchange: 0,
    consumed: 20,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi97',
    programId: 'p_mar_3',
    itemId: 'pencil',
    itemName: 'Pencil',
    unit: 'Nos',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi98',
    programId: 'p_mar_3',
    itemId: 'eraser',
    itemName: 'Eraser',
    unit: 'Nos',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 110,
    returned: 0,
    noReturn: 110,
    exchange: 0,
    consumed: 110,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi99',
    programId: 'p_mar_3',
    itemId: 'stapler-pins',
    itemName: 'Stapler Pins - 24/6',
    unit: 'Box',
    date: '2026-03-05',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 10,
    returned: 0,
    noReturn: 10,
    exchange: 0,
    consumed: 10,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi100',
    programId: 'p_mar_16',
    itemId: 'id-card-holders',
    itemName: 'ID Card Holders - Transparent',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi101',
    programId: 'p_mar_16',
    itemId: 'lanyard-isha',
    itemName: 'Lanyard - Isha Branded',
    unit: 'Nos',
    date: '2026-03-25',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 150,
    returned: 0,
    noReturn: 150,
    exchange: 0,
    consumed: 150,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi102',
    programId: 'p_mar_10',
    itemId: 'id-card-holders',
    itemName: 'ID Card Holders - Transparent',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi103',
    programId: 'p_mar_10',
    itemId: 'lanyard-isha',
    itemName: 'Lanyard - Isha Branded',
    unit: 'Nos',
    date: '2026-03-19',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 100,
    returned: 0,
    noReturn: 100,
    exchange: 0,
    consumed: 100,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi104',
    programId: 'p_mar_5',
    itemId: 'whiteboard-marker',
    itemName: 'Whiteboard Marker - Set of 4',
    unit: 'Set',
    date: '2026-03-08',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 2,
    returned: 0,
    noReturn: 2,
    exchange: 0,
    consumed: 2,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 0,
    status: '🚫 Non-Returnable',
    pocName: 'Shubham',
    isConsumable: true
  },
  {
    id: 'pi105',
    programId: 'p_mar_5',
    itemId: 'stapler',
    itemName: 'Stapler - Heavy Duty',
    unit: 'Nos',
    date: '2026-03-08',
    expectedReturnDate: '2026-03-11',
    collectedBy: 'Shubham',
    issuer: 'Admin',
    issued: 1,
    returned: 0,
    noReturn: 0,
    exchange: 0,
    consumed: 0,
    missing: 0,
    damaged: 0,
    discarded: 0,
    pending: 1,
    status: '🟠 DUE FOR RETURN ⏰',
    pocName: 'Shubham',
    isConsumable: false
  },
];
